language: objective-c

xcode_workspace: Phoenix.xcworkspace
xcode_scheme: Phoenix

xcode_sdk: macosx11.0

notifications:
  email: false

before_install:
  - gem install xcpretty
  - npm install

matrix:
  include:
    - osx_image: xcode12.2
    - osx_image: xcode12.1
    - osx_image: xcode12
