name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-10.15
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16.6.2
      - uses: sersoft-gmbh/xcodebuild-action@v1
        with:
          workspace: Phoenix.xcworkspace
          scheme: Phoenix
          action: test build
